### ISSUE TITLE
how is the performance that centerpoint downsample 32x?

### ISSUE THREAD

**Issue by AndyYuan96** [dvlab-research/VoxelNeXt#1]
Hi, thanks for sharing the code, after reading paper, I see you use 32x feature to enlarge ERF, and centerpoint's max downsample is 16 from 2d_backbone, so I just wonder whether you have the performance that centerpoint also use max downsample 32 to make a fair compare。
What's more, after reading the paper, I thought that if we change centerpoint to full sparse(more downsample in 3d backbone and no 2d backbone and sparse centerhead), we should have similar performance with centerpoint, but very efficient for long range object detection, do you think is reasonable?

**Comment by yukang2017** [comment]
Hi Andy,

Thanks for your interest in our paper.

I never tried to use CenterPoint with the 32x backbone. Thanks for your remind. I will add this ablation.
In addition, I suppose the comparison is fair. The 32x backbone is to improve ERF, while the dense neck / rpn of CenterPoint is also for this purpose. Our design, "32x backbone" serves as a substitute of "8x backbone + dense neck". Anyway, I will do this experiment. I will report the result here after I finish it.

Yes, this is reasonable. VoxelNeXt is just what you said, more downsample 3D backbone + sparse head. 


Regards,
Yukang Chen

**Comment by AndyYuan96** [comment]
> Hi Andy,
> 
> Thanks for your interest in our paper.
> 
> I never tried to use CenterPoint with the 32x backbone before. Thanks for your remind. I will add this ablation. In addition, I suppose the comparison is fair. The 32x backbone is to improve ERF, while the dense neck / rpn of CenterPoint is also for this purpose. Our design, "32x backbone" serves as a substitute of "8x backbone + dense neck". Anyway, I will do this experiment. I will report the result here after I finish it.
> 
> Yes, this is reasonable. VoxelNeXt is just what you said, more downsample 3D backbone + sparse head.
> 
> Regards, Yukang Chen

thanks for the reply.
