### ISSUE TITLE
waymo val result

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/VoxelNeXt#10]
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/44592986/229482811-9d128eeb-fb2c-45ae-a0d3-cfe25f2cd15f.png">
@yukang2017  hi yukang! could you please tell me what config file you use for the above result on waymo val dataset marked by red box ? I reproduce the result with `voxelnext_ioubranch.yaml` for 12 epochs but it didn't be as close as the result in paper.

**Comment by DezeZhao** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/44592986/229483630-aa035712-6c91-47e2-9d6f-3ee58e1b8f54.png">

**Comment by DezeZhao** [comment]
> <img alt="image" width="1405" src="https://user-images.githubusercontent.com/44592986/229482811-9d128eeb-fb2c-45ae-a0d3-cfe25f2cd15f.png">
> 
> @yukang2017 hi yukang! could you please tell me what config file you use for the above result on waymo val dataset marked by red box ? I reproduce the result with `voxelnext_ioubranch.yaml` for 12 epochs but it didn't be as close as the result in paper.

Or could you please share checkpoint with me?

**Comment by yukang2017** [comment]
Hi Deze,

VoxelNeXt**K3** is an enhanced version of VoxelNeXt with larger model size. This config file for it is [voxelnext_ioubranch_large.yaml](https://github.com/dvlab-research/VoxelNeXt/blob/master/tools/cfgs/waymo_models/voxelnext_ioubranch_large.yaml).
Sorry for the unclearness. I will highlight this point in the README.

Please contact me via WeChat 13261057196. I will send you the checkpoint.


Regards,
Yukang Chen

**Comment by yukang2017** [comment]
This is the detailed result for VoxelNeXtK3.

```
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7816 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7770 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6985 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6942 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.8147 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.7630 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.7348 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.6863
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.7605 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.7490 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.7329 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.7218
```

This is the detailed result for VoxelNeXt-2D.
```
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7794 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7747 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6968 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6925 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.8024 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.7347 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.7223 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.6588
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.7333
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.7220
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.7065
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.6956
```

**Comment by pycoco** [comment]
> OK thank you.

Did you reproduce the results on waymo with master configs?
