### ISSUE TITLE
Large model for nuscenes

### ISSUE THREAD

**Issue by c7huang** [dvlab-research/VoxelNeXt#11]
Hi, thanks for publishing the code for your work!

I noticed the large model with 256 channels provides better results on Waymo, but the models for nuscenes and argoverse are not scaled up and use 128 channels. Is there a particular reason for this decision, or do you think the same scaling work on these datasets as well?

**Comment by yukang2017** [comment]
Hi,

I only tried the large model on Waymo before, but not on nuScenes or Argoverse2 before. I think it should also be helpful.

Regards,
Yukang Chen

**Comment by c7huang** [comment]
Thanks!
