### ISSUE TITLE
Sample interval for Waymo model

### ISSUE THREAD

**Issue by c7huang** [dvlab-research/VoxelNeXt#12]
Hi, thanks again for publishing the code for your work!

The `waymo_dataset.yaml` config file used by the Waymo models have `SAMPLED_INTERVAL` for train split set to `5`, i.e. 20% of Waymo. However, the reported results are included in the 100% Waymo table in `OpenPCDet` repo.

Given that the model is only trained for 12 epochs, I assume the `SAMPLED_INTERVAL` needs to be set to 1, i.e. 100% Waymo, to reproduce the results?

**Comment by yukang2017** [comment]
Hi,

Yes. The result is trained on 100% Waymo. 


Regards,
Yukang Chen

**Comment by c7huang** [comment]
Thanks for the clarification!
