### ISSUE TITLE
About the FLOPs.

### ISSUE THREAD

**Issue by AlmoonYsl** [dvlab-research/VoxelNeXt#21]
Hi, thanks for your excellent work.
As shown in Tab. 1, the FLOPs is calculated for sparse cnn and head separately. I noticed that the FLOPs of sparse cnn and head (VoxelNeXt) is 33.6G and 5.1G. So, I want to know whether the sparse conv in 3D backbone and head (VoxelNeXt) is considered in calculation. AFAK, the mmcv and fvcore do not support the FLOPs calculation for sparse conv. 
Besides, the head of CenterPoint is consists of 2D conv, which is supported by mmcv and fvcore.

**Comment by AlmoonYsl** [comment]
> Hi,
> 
> spconv is included in FLOPs calculation. We use the FLOPs calculation tool in https://github.com/CVMI-Lab/SparseKD

Got it. Thanks for your reply!

**Comment by yBeOne** [comment]
Where is the FLOPs calculation tool in SparseKD?

**Comment by yukang2017** [comment]
Please refer to this.

https://github.com/CVMI-Lab/SparseKD/blob/8572093edc77d4217f7596d9e1de68c6dc77e420/pcdet/utils/common_utils.py#L344
