### ISSUE TITLE
trainning speed

### ISSUE THREAD

**Issue by HuangVictorAuto** [dvlab-research/VoxelNeXt#22]
Hello, Thanks for your great work. Can you share some data about the training settings and training speed?

**Comment by yukang2017** [comment]
Hi,

You can refer to this issue. Because my machine is very very old. The training time for me might be several days. But the other said that he took 4-10 hours to train on Waymo.

https://github.com/dvlab-research/VoxelNeXt/issues/20


Regards,
Yukang Chen
