### ISSUE TITLE
waymo results reference

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/VoxelNeXt#25]
<img width="1338" alt="image" src="https://github.com/dvlab-research/VoxelNeXt/assets/44592986/d5001004-9453-44ef-9180-9379288353da">

hi @yukang2017 , could you please show me where the results of CenterPoint and SST you refer?
for CenterPoint, original paper results are not the same as you provided, for SST, I can only find Veh. and Ped. results from the original paper. Looking forward to your reply.

**Comment by yukang2017** [comment]
Hi,

I refer these from this paper.

Fully Sparse 3D Object Detection, NeurIPS 2022.
https://arxiv.org/pdf/2207.10035.pdf

Regards,
Yukang Chen

**Comment by DezeZhao** [comment]
OK  thank you! I get it.

**Comment by DezeZhao** [comment]
Another question: Have you ever tried to train voxelnext_ioubranch and voxelnext_ioubranch_large configs with 30 epochs to get even better results?

**Comment by DezeZhao** [comment]
yeah, thank you for your reply in time.
