### ISSUE TITLE
The results on the kitti dataset are not good？

### ISSUE THREAD

**Issue by 910399614** [dvlab-research/VoxelNeXt#27]
Hi, I followed the  released config file to train VoxelNeXt on the KITTI, but the detection results don't seem to be good?

Here is the epoch with the best results trained on my machine.

2023-05-30 13:25:51,687   INFO  *************** Performance of EPOCH 72 *****************
2023-05-30 13:25:51,688   INFO  Generate label finished(sec_per_example: 0.0634 second).
2023-05-30 13:25:51,688   INFO  recall_roi_0.3: 0.000000
2023-05-30 13:25:51,688   INFO  recall_rcnn_0.3: 0.935357
2023-05-30 13:25:51,688   INFO  recall_roi_0.5: 0.000000
2023-05-30 13:25:51,688   INFO  recall_rcnn_0.5: 0.873562
2023-05-30 13:25:51,688   INFO  recall_roi_0.7: 0.000000
2023-05-30 13:25:51,689   INFO  recall_rcnn_0.7: 0.633500
2023-05-30 13:25:51,715   INFO  Average predicted number of objects(3769 samples): 12.604
2023-05-30 13:26:09,365   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:90.4678, 89.2926, 88.3760
bev  AP:89.0743, 86.4952, 83.4077
3d   AP:86.5793, 76.6896, 74.6050
aos  AP:90.45, 89.11, 88.13
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:95.5828, 91.9155, 90.6527
bev  AP:91.6419, 87.5357, 85.0153
3d   AP:87.9198, 77.8969, 75.1770
aos  AP:95.56, 91.71, 90.39
Car AP@0.70, 0.50, 0.50:
bbox AP:90.4678, 89.2926, 88.3760
bev  AP:94.7389, 89.6084, 89.1113
3d   AP:94.6626, 89.5168, 88.9023
aos  AP:90.45, 89.11, 88.13
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:95.5828, 91.9155, 90.6527
bev  AP:96.8324, 94.3452, 93.6283
3d   AP:96.7766, 94.1481, 91.5978
aos  AP:95.56, 91.71, 90.39
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:76.9811, 73.3218, 69.6398
bev  AP:65.7048, 61.0455, 56.5700
3d   AP:62.2981, 56.9214, 52.1742
aos  AP:75.42, 71.20, 67.12
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:77.9146, 73.9838, 70.5503
bev  AP:66.2811, 60.9713, 55.7163
3d   AP:61.5019, 56.5423, 50.7263
aos  AP:76.24, 71.67, 67.70
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:76.9811, 73.3218, 69.6398
bev  AP:82.2534, 79.8235, 76.3670
3d   AP:82.1528, 79.5656, 76.0224
aos  AP:75.42, 71.20, 67.12
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:77.9146, 73.9838, 70.5503
bev  AP:84.9853, 81.9345, 77.8001
3d   AP:84.8836, 81.4974, 77.4063
aos  AP:76.24, 71.67, 67.70
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:87.4056, 73.9096, 71.1011
bev  AP:84.3527, 69.5915, 65.2032
3d   AP:81.7647, 66.3772, 62.1164
aos  AP:87.32, 73.52, 70.74
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:89.9100, 75.6070, 71.9232
bev  AP:86.1329, 70.2481, 66.1244
3d   AP:82.1792, 65.8815, 61.9532
aos  AP:89.81, 75.18, 71.51
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:87.4056, 73.9096, 71.1011
bev  AP:86.7529, 71.9742, 69.1377
3d   AP:86.7529, 71.9742, 69.1377
aos  AP:87.32, 73.52, 70.74
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:89.9100, 75.6070, 71.9232
bev  AP:89.0928, 73.4686, 69.6789
3d   AP:89.0928, 73.4686, 69.6789
aos  AP:89.81, 75.18, 71.51

**Comment by yukang2017** [comment]
https://github.com/dvlab-research/VoxelNeXt/issues/16

This is the result I get from this config. 

I just wrote this config for an example on KITTI, without any hyper-parameters tuning. I think some hyper-parameters can be adjusted to get better performance.
