### ISSUE TITLE
spatial voxel pruning

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/VoxelNeXt#7]
@yukang2017 hi, yukang! I am confused about the spatial voxel pruning module in the code.(spconv_backbone_voxelnext）  It seemed that you didn't use it in the 3d backbone while downsampling, were you?

**Comment by yukang2017** [comment]
Hi Deze,

Thanks for your interest in our work. I put the backbone that contains the spatial voxel pruning in the other files.

The code of spatial voxel pruning backbone exists in 
https://github.com/dvlab-research/VoxelNeXt/blob/c1a45ffe01ef12fd614bd12447145f3ee8a5eb96/pcdet/models/backbones_3d/spconv_backbone_voxelnext_sps.py#L94
and 
https://github.com/dvlab-research/VoxelNeXt/blob/923c2fdddcd928fa300311fa5609867efb6703bf/pcdet/models/backbones_3d/spconv_backbone_voxelnext2d_sps.py#L90

For using them, you can simply change `VoxelResBackBone8xVoxelNeXt` to `VoxelResBackBone8xVoxelNeXtSPS` or `VoxelResBackBone8xVoxelNeXt2D` to `VoxelResBackBone8xVoxelNeXt2DSPS` in config files.


Regards,
Yukang Chen
