### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by naren2cmu** [dvlab-research/VoxelNeXt#8]
Hi, 

The command for evaulation in README.md uses tools/scripts/dist_tesh.sh
![image](https://user-images.githubusercontent.com/113138659/228963061-5e73bf75-23c9-4d72-9ab9-c1867a99108b.png)

However, dist_test.sh does not seem to be there in tools/scripts

![image](https://user-images.githubusercontent.com/113138659/228963199-9e7f21f2-2d7d-4b2d-a6b7-5929e0212983.png)

Could you kindly help with this?

Thank you
Naren

**Comment by yukang2017** [comment]
Hi Naren,

Sorry for missing them. I have uploaded them just now.

https://github.com/dvlab-research/VoxelNeXt/blob/master/tools/scripts/dist_test.sh


Regards,
Yukang Chen

**Comment by yukang2017** [comment]
Hi Naren,

The test.py is [here](https://github.com/dvlab-research/VoxelNeXt/blob/master/tools/test.py). I think you should `cd tools` first.
Thanks for your remind for the broken link. I have modify the link.
https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md


Regards,
Yukang Chen

**Comment by naren2cmu** [comment]
Thanks Yukang. 

I tried that. The test.py was found this time. However, it is running into other errors. 

This is the command I ran: 

`bash scripts/dist_test.sh 1 --cfg_file /mnt/tools/cfgs/nuscenes_models/cbgs_voxel0075_voxelnext.yaml --ckpt /mnt/VoxelNeXt/voxelnext_nuscenes_kernel1.pth`

This is what I got. 
`+ NGPUS=1
+ PY_ARGS='--cfg_file /mnt/tools/cfgs/nuscenes_models/cbgs_voxel0075_voxelnext.yaml --ckpt /mnt/VoxelNeXt/voxelnext_nuscenes_kernel1.pth'
+ python -m torch.distributed.launch --nproc_per_node=1 test.py --launcher pytorch --cfg_file /mnt/tools/cfgs/nuscenes_models/cbgs_voxel0075_voxelnext.yaml --ckpt /mnt/VoxelNeXt/voxelnext_nuscenes_kernel1.pth
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from eval_utils import eval_utils
  File "/mnt/VoxelNeXt/tools/eval_utils/eval_utils.py", line 8, in <module>
    from pcdet.models import load_data_to_gpu
  File "../pcdet/__init__.py", line 4, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'pcdet.version'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'test.py', '--local_rank=0', '--launcher', 'pytorch', '--cfg_file', '/mnt/tools/cfgs/nuscenes_models/cbgs_voxel0075_voxelnext.yaml', '--ckpt', '/mnt/VoxelNeXt/voxelnext_nuscenes_kernel1.pth']' returned non-zero exit status 1.`

It seems that the pcdet.version is not being found. 

Also, you fixed the link to prepare the datasets. But I think you forgot to fix the link to install the environment. That is still broken. 
![image](https://user-images.githubusercontent.com/113138659/229349357-20a05dc7-70dc-4f43-88f7-c21598b96c1e.png)


Thank you
Naren

**Comment by yukang2017** [comment]
Hi Naren,

Did you install the pcdet by `python setup.py develop`?

It should be fixed if it has been installed, because of this line.
https://github.com/dvlab-research/VoxelNeXt/blob/1d67ec6daee87b730897006b248e9e4fcd05eb37/setup.py#L32

Thanks for your remind. I have updated the install document.


Regards,
Yukang Chen
