### ISSUE TITLE
code robustness

### ISSUE THREAD

**Issue by DezeZhao** [dvlab-research/VoxelNeXt#9]
https://github.com/dvlab-research/VoxelNeXt/blob/c523b39ef747e5a6e8bdbcf0d05c306048e839f2/pcdet/models/dense_heads/voxelnext_head_maxpool.py#L400

I think it should add checking of `mask_cls` as follows:
```
if mask_cls.sum() == 0:
    continue
```

**Comment by DezeZhao** [comment]
https://github.com/dvlab-research/VoxelNeXt/blob/c523b39ef747e5a6e8bdbcf0d05c306048e839f2/pcdet/models/dense_heads/voxelnext_head_maxpool.py#L69
https://github.com/dvlab-research/VoxelNeXt/blob/c523b39ef747e5a6e8bdbcf0d05c306048e839f2/pcdet/models/dense_heads/voxelnext_head_maxpool.py#L401

here `self.rectifier` is not defined, definition should be added at line 69.

**Comment by yukang2017** [comment]
Thanks for your remind. Sorry for missing the `self.rectifier`. I have updated it.
